# action.yml
name: 'GitHub Followers'
description: 'Greet someone and record the time'
inputs:
  login:  # id of login
    description: 'Who to greet'
    required: true
    default: 'login'
  pat: # id of pat
    description: 'Who to greet'
    required: true
    default: 'pat'
  readme: # id of readme
    description: 'Who to greet'
    required: true
    default: 'README.md'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.login }}
    - ${{ inputs.pat }}
    - ${{ inputs.readme }}