# action.yml
name: 'Display GitHub Followers'
description: 'A GitHub Action ranks your followers and renders those data into HTML elements so that those ranked followers can be easily displayed in your GitHub profile.'
author: 'Jie Ding <me@jieding.io>'
inputs:
  login:  # your login id
    description: 'your login id'
    required: true
    default: 'login'
  pat: # your PAT
    description: 'Your PAT'
    required: true
    default: 'pat'
  readme: # the file followers information should be sent to
    description: 'Who to greet'
    required: false
    default: 'README.md'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/jieding/github-followers-action:v1.0.0'
  args:
    - ${{ inputs.login }}
    - ${{ inputs.pat }}
    - ${{ inputs.readme }}