name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Manage dependency
      run: go mod tidy

    - name: Run
      run: |
        echo "execute go program"
        go run ./followers.go -u ${{ github.repository_owner }} -p ${{ secrets.PERSONAL_ACCESS_TOKEN }} -f README.md