on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test github-follower
    steps:
      - name: use github-follower
        id: hello
        uses: JieDing/github-followers@main
        env:
          login: ${{ github.repository_owner }}
          pat: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          readme: 'README.md'
